import { getSupabaseClient, requireSupabaseSession } from "./cloud";
import type { Appointment, AppNotification } from "../types/crm";

type AppointmentRow = Record<string, unknown>;
type NotificationRow = Record<string, unknown>;

export function mapDbAppointment(row: AppointmentRow): Appointment {
  const noteData = parseAppointmentNotes(row.notes);
  return {
    id: String(row.id ?? ""),
    customerId: row.customer_id ? String(row.customer_id) : undefined,
    customerName: String(row.customer_name ?? noteData.customerName ?? "Cliente"),
    customerEmail: row.customer_email ? String(row.customer_email) : noteData.customerEmail,
    customerWhatsapp: row.customer_whatsapp ? String(row.customer_whatsapp) : noteData.customerWhatsapp,
    serviceId: row.service_id ? String(row.service_id) : undefined,
    service: String(row.service ?? noteData.service ?? "Servicio"),
    serviceSubtype: row.service_subtype ? String(row.service_subtype) : noteData.serviceSubtype,
    date: String(row.appointment_date ?? ""),
    start: String(row.start_time ?? "").slice(0, 5),
    end: String(row.end_time ?? "").slice(0, 5),
    status: String(row.status ?? "creada") as Appointment["status"],
    cost: Number(row.cost ?? 0),
    discountPercent: Number(row.discount_percent ?? 0),
    advancePaymentStatus: noteData.advancePaymentStatus === "pagado" ? "pagado" : "pendiente",
    advanceRequestedAt: noteData.advanceRequestedAt,
    advancePaidAt: noteData.advancePaidAt,
    posSaleId: noteData.posSaleId,
    orderFolio: noteData.orderFolio,
    autoGenerated: Boolean(row.auto_generated ?? false),
    parentAppointmentId: row.parent_appointment_id ? String(row.parent_appointment_id) : undefined,
    confirmationToken: row.confirmation_token ? String(row.confirmation_token) : noteData.confirmationToken,
    notes: row.notes ? String(row.notes) : undefined,
  };
}

export function mapDbNotification(row: NotificationRow): AppNotification {
  return {
    id: String(row.id ?? ""),
    appointmentId: String(row.appointment_id ?? ""),
    title: String(row.title ?? "Notificación"),
    message: String(row.message ?? ""),
    kind: row.kind ? String(row.kind) : undefined,
    date: String(row.target_date ?? row.created_at ?? "").slice(0, 10),
    read: Boolean(row.read ?? false),
    seenAt: row.seen_at ? String(row.seen_at) : undefined,
  };
}

export function appointmentToDb(appointment: Omit<Appointment, "id"> | Appointment) {
  const notes = buildAppointmentNotes(appointment);
  return {
    customer_id: appointment.customerId ?? null,
    customer_name: appointment.customerName,
    customer_email: appointment.customerEmail ?? null,
    customer_whatsapp: appointment.customerWhatsapp ?? null,
    service_id: appointment.serviceId ?? null,
    service: appointment.service,
    service_subtype: appointment.serviceSubtype ?? null,
    appointment_date: appointment.date,
    start_time: appointment.start,
    end_time: appointment.end,
    status: appointment.status,
    cost: Number(appointment.cost ?? 0),
    discount_percent: Number(appointment.discountPercent ?? 0),
    auto_generated: Boolean(appointment.autoGenerated ?? false),
    parent_appointment_id: appointment.parentAppointmentId ?? null,
    confirmation_token: appointment.confirmationToken ?? null,
    notes,
  };
}

function buildAppointmentNotes(appointment: Omit<Appointment, "id"> | Appointment) {
  const data = {
    confirmationToken: appointment.confirmationToken ?? "",
    customerName: appointment.customerName,
    customerEmail: appointment.customerEmail ?? "",
    customerWhatsapp: appointment.customerWhatsapp ?? "",
    service: appointment.service,
    serviceSubtype: appointment.serviceSubtype ?? "",
    advancePaymentStatus: appointment.advancePaymentStatus ?? "pendiente",
    advanceRequestedAt: appointment.advanceRequestedAt ?? "",
    advancePaidAt: appointment.advancePaidAt ?? "",
    posSaleId: appointment.posSaleId ?? "",
    orderFolio: appointment.orderFolio ?? "",
  };
  const existingNotes = appointment.notes?.replace(/crm_confirmation_token:[^\n]+/g, "").replace(/crm_appointment_data:{.*}/g, "").trim();
  return [
    existingNotes,
    appointment.confirmationToken ? `crm_confirmation_token:${appointment.confirmationToken}` : "",
    `crm_appointment_data:${JSON.stringify(data)}`,
  ].filter(Boolean).join("\n");
}

function parseAppointmentNotes(notes: unknown) {
  const value = typeof notes === "string" ? notes : "";
  const tokenMatch = value.match(/crm_confirmation_token:([^\s]+)/);
  const dataMatch = value.match(/crm_appointment_data:({.*})/);
  const parsed: Partial<Appointment> & { confirmationToken?: string } = dataMatch ? (() => {
    try {
      return JSON.parse(dataMatch[1]) as Partial<Appointment> & { confirmationToken?: string };
    } catch {
      return {};
    }
  })() : {};
  return {
    ...parsed,
    confirmationToken: parsed.confirmationToken || tokenMatch?.[1],
  };
}

function removeUnsupportedColumn(record: Record<string, unknown>, errorMessage: string) {
  const match = errorMessage.match(/'([^']+)' column/);
  const column = match?.[1];
  if (!column || !(column in record)) return false;
  delete record[column];
  return true;
}

export async function fetchSupabaseAppointments() {
  const supabase = await requireSupabaseSession();
  const { data, error } = await supabase
    .from("appointments")
    .select("*")
    .order("appointment_date", { ascending: true })
    .order("start_time", { ascending: true });
  if (error) throw error;
  return (data ?? []).map((row) => mapDbAppointment(row as AppointmentRow));
}

export async function createSupabaseAppointment(appointment: Omit<Appointment, "id">) {
  const supabase = await requireSupabaseSession();
  const record = appointmentToDb(appointment);
  for (let attempt = 0; attempt < 12; attempt += 1) {
    const { data, error } = await supabase
      .from("appointments")
      .insert(record)
      .select("*")
      .single();
    if (!error) return mapDbAppointment(data as AppointmentRow);
    if (error.code === "PGRST204" && removeUnsupportedColumn(record, error.message)) continue;
    throw error;
  }
  throw new Error("No se pudo guardar la cita en la nube.");
}

export async function updateSupabaseAppointment(appointmentId: string, patch: Partial<Appointment>) {
  const supabase = await requireSupabaseSession();
  const record: Record<string, unknown> = {};
  if (patch.customerName !== undefined) record.customer_name = patch.customerName;
  if (patch.customerId !== undefined) record.customer_id = patch.customerId ?? null;
  if (patch.customerEmail !== undefined) record.customer_email = patch.customerEmail ?? null;
  if (patch.customerWhatsapp !== undefined) record.customer_whatsapp = patch.customerWhatsapp ?? null;
  if (patch.serviceId !== undefined) record.service_id = patch.serviceId ?? null;
  if (patch.service !== undefined) record.service = patch.service;
  if (patch.serviceSubtype !== undefined) record.service_subtype = patch.serviceSubtype ?? null;
  if (patch.date !== undefined) record.appointment_date = patch.date;
  if (patch.start !== undefined) record.start_time = patch.start;
  if (patch.end !== undefined) record.end_time = patch.end;
  if (patch.status !== undefined) record.status = patch.status;
  if (patch.cost !== undefined) record.cost = Number(patch.cost ?? 0);
  if (patch.discountPercent !== undefined) record.discount_percent = Number(patch.discountPercent ?? 0);
  if (patch.autoGenerated !== undefined) record.auto_generated = Boolean(patch.autoGenerated);
  if (patch.parentAppointmentId !== undefined) record.parent_appointment_id = patch.parentAppointmentId ?? null;
  if (patch.confirmationToken !== undefined) record.confirmation_token = patch.confirmationToken ?? null;
  if (patch.notes !== undefined) record.notes = patch.notes ?? null;
  if (
    patch.advancePaymentStatus !== undefined
    || patch.advanceRequestedAt !== undefined
    || patch.advancePaidAt !== undefined
    || patch.posSaleId !== undefined
    || patch.orderFolio !== undefined
  ) {
    const { data, error } = await supabase.from("appointments").select("*").eq("id", appointmentId).single();
    if (error) throw error;
    record.notes = buildAppointmentNotes({ ...mapDbAppointment(data as AppointmentRow), ...patch });
  }

  for (let attempt = 0; attempt < 12; attempt += 1) {
    const { data, error } = await supabase.from("appointments").update(record).eq("id", appointmentId).select("*").single();
    if (!error) return mapDbAppointment(data as AppointmentRow);
    if (error.code === "PGRST204" && removeUnsupportedColumn(record, error.message)) continue;
    throw error;
  }
  throw new Error("No se pudo actualizar la cita en la nube.");
}

export async function deleteSupabaseAppointments(appointmentIds: string[]) {
  if (appointmentIds.length === 0) return;
  const supabase = await requireSupabaseSession();
  const { error } = await supabase.from("appointments").delete().in("id", appointmentIds);
  if (error) throw error;
}

export async function updateAppointmentStatusByToken(token: string, status: "aceptada" | "rechazada") {
  const supabase = getSupabaseClient();
  const functionResult = await supabase.functions.invoke("appointment-confirmation", {
    body: { token, status },
  });
  if (!functionResult.error && functionResult.data?.ok && functionResult.data.appointment) {
    return mapDbAppointment(functionResult.data.appointment as AppointmentRow);
  }
  if (functionResult.error) throw functionResult.error;
  return null;
}

export async function findAppointmentByTokenInSupabase(token: string) {
  const supabase = getSupabaseClient();
  const result = await supabase.functions.invoke("appointment-confirmation", {
    body: { token, action: "lookup" },
  });
  if (result.error) throw result.error;
  if (!result.data?.ok || !result.data.appointment) return null;
  return mapDbAppointment(result.data.appointment as AppointmentRow);
}

export async function enqueueAppointmentStatusNotification(appointment: Appointment, status: "aceptada" | "rechazada") {
  const supabase = await requireSupabaseSession();
  const accepted = status === "aceptada";
  const title = accepted ? "Cita confirmada" : "Cita rechazada por cliente";
  const message = accepted
    ? `${appointment.customerName} confirmó su cita de ${appointment.service} (${appointment.date} ${appointment.start}).`
    : `${appointment.customerName} rechazó su cita de ${appointment.service} (${appointment.date} ${appointment.start}).`;
  const kind = accepted ? "appointment_confirmed" : "appointment_status_changed";
  const dedupe_key = `appointment:${appointment.id}:status:${status}`;

  const record = {
    appointment_id: appointment.id,
    title,
    message,
    kind,
    target_date: appointment.date,
    read: false,
    dedupe_key,
  };

  const { data: existing } = await supabase
    .from("notifications")
    .select("id")
    .eq("dedupe_key", dedupe_key)
    .maybeSingle();

  if (existing?.id) {
    await supabase.from("notifications").update(record).eq("id", existing.id);
    return;
  }

  const { error } = await supabase.from("notifications").insert(record);
  if (error && error.code !== "23505") throw error;
}
