export type LeadStage = "nuevo" | "contactado" | "propuesta" | "negociacion" | "ganado" | "perdido";
export type Priority = "baja" | "media" | "alta";

export interface Customer {
  id: string;
  customerNumber?: string;
  name: string;
  company: string;
  email: string;
  phone: string;
  rfc?: string;
  profileImageUrl?: string;
  profileImagePath?: string;
  status: "activo" | "prospecto" | "inactivo";
  owner: string;
  createdAt: string;
  serviceType?: string;
  birthDate?: string;
  gender?: "femenino" | "masculino" | "otro";
  whatsapp?: string;
  address?: string;
  preferredSchedule?: string;
  firstVisitDate?: string;
  referredBy?: string;
  medicalAlerts?: string;
  notes?: string;
  allergies?: string[];
  surgeries?: string[];
  diseases?: string[];
  previousProcedures?: string;
  thyroidIssues?: "si" | "no" | "";
  bodyProducts?: string;
  previousBotoxOrSubstance?: "si" | "no" | "";
  previousSubstanceDetails?: string;
  secondaryReactions?: "si" | "no" | "";
  seafoodAllergy?: "si" | "no" | "";
  seafoodAllergyDetails?: string;
  healingProblems?: "si" | "no" | "";
  preferredContactChannel?: "email" | "whatsapp";
}

export interface CustomerServiceHistory {
  id: string;
  customerId: string;
  serviceId?: string;
  serviceName: string;
  serviceDate?: string;
  amount?: number;
  paymentStatus: "sin_registro" | "pendiente" | "pagado";
  paymentMethod?: "efectivo" | "tarjeta" | "transferencia" | "bill_packet" | "otro";
  receiptFolio?: string;
  receiptSentAt?: string;
  receiptEmail?: string;
  notes?: string;
  sourceType: "importacion" | "manual" | "pos" | "cita";
  sourceReference?: string;
  editable: boolean;
}

export interface Contact {
  id: string;
  customerId: string;
  name: string;
  role: string;
  email: string;
  phone: string;
}

export interface Lead {
  id: string;
  title: string;
  customerId: string;
  stage: LeadStage;
  value: number;
  probability: number;
  owner: string;
  nextStep: string;
  expectedClose: string;
  priority: Priority;
}

export interface Activity {
  id: string;
  leadId?: string;
  customerId?: string;
  title: string;
  type: "llamada" | "correo" | "reunion" | "tarea";
  dueDate: string;
  completed: boolean;
}

export interface Note {
  id: string;
  customerId?: string;
  leadId?: string;
  title: string;
  content: string;
  createdAt: string;
}

export interface Appointment {
  id: string;
  customerId?: string;
  customerName: string;
  customerEmail?: string;
  customerWhatsapp?: string;
  serviceId?: string;
  service: string;
  serviceSubtype?: string;
  date: string;
  start: string;
  end: string;
  status: "creada" | "enviada" | "aceptada" | "rechazada" | "reagendada" | "completada" | "cancelada";
  cost?: number;
  discountPercent?: number;
  advancePaymentStatus?: "pendiente" | "pagado";
  advanceRequestedAt?: string;
  advancePaidAt?: string;
  posSaleId?: string;
  orderFolio?: string;
  autoGenerated?: boolean;
  parentAppointmentId?: string;
  confirmationToken?: string;
  notes?: string;
}

export interface AppNotification {
  id: string;
  appointmentId: string;
  title: string;
  message: string;
  kind?: string;
  date: string;
  read: boolean;
  seenAt?: string;
}

export interface CashSession {
  id: string;
  openedAt: string;
  closedAt?: string;
  userName: string;
  openingAmount: number;
  status: "abierta" | "cerrada";
  posLocked?: boolean;
}

export interface PosSaleItem {
  id: string;
  serviceId?: string;
  treatmentId?: string;
  serviceName: string;
  quantity: number;
  unitPrice: number;
  total: number;
}

export interface Service {
  id: string;
  name: string;
  description?: string;
  category?: string;
  price: number;
  active: boolean;
  ownerUserId?: string;
  isShared?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface PosSale {
  id: string;
  folio: string;
  cashSessionId: string;
  createdAt: string;
  userName: string;
  customerId?: string;
  customerName?: string;
  subtotal: number;
  total: number;
  advanceAmount?: number;
  paidAmount?: number;
  paymentType?: "anticipo" | "garantia" | "sin_anticipo";
  paymentStatus?: "anticipo" | "anticipo_pagado" | "pendiente" | "garantia" | "pagado";
  paymentMethod: "efectivo" | "tarjeta" | "transferencia" | "bill_packet";
  paymentInstallments?: 3 | 6;
  appointmentId?: string;
  items: PosSaleItem[];
}

export type SalesHistorySource = "importacion" | "manual" | "cita" | "pos";

export interface SalesHistoryRecord {
  id: string;
  customerId?: string;
  customerName: string;
  customerEmail?: string;
  customerPhone?: string;
  serviceId?: string;
  serviceName: string;
  saleDate: string;
  amount?: number;
  paymentStatus: "sin_registro" | "pendiente" | "pagado";
  paymentMethod?: "efectivo" | "tarjeta" | "transferencia" | "bill_packet" | "otro";
  receiptFolio?: string;
  sourceType: SalesHistorySource;
  sourceReference?: string;
  createdAt: string;
}

export interface UserSession {
  name: string;
  email: string;
  role: "Administrador" | "Vendedor";
  permissions?: Record<string, boolean>;
  avatarUrl?: string;
  avatarPath?: string;
  firstName?: string;
  lastName?: string;
  address?: string;
  companyName?: string;
}
