import { CheckCircle2, Plus } from "lucide-react";
import { useState } from "react";
import { Button } from "../components/ui/Button";
import { Card } from "../components/ui/Card";
import { Input } from "../components/ui/Input";
import { PageHeader } from "../components/ui/PageHeader";
import { Select } from "../components/ui/Select";
import { useCrmStore } from "../store/crmStore";
import { prettyDate } from "../utils/format";
export function ActivitiesPage() { const activities = useCrmStore((state) => state.activities); const leads = useCrmStore((state) => state.leads); const addActivity = useCrmStore((state) => state.addActivity); const toggleActivity = useCrmStore((state) => state.toggleActivity); const [form, setForm] = useState({ leadId: leads[0]?.id ?? "", title: "", type: "llamada" as "llamada" | "correo" | "reunion" | "tarea", dueDate: "2026-05-20" }); return <><PageHeader eyebrow="Seguimiento" title="Actividades comerciales" description="Gestiona pendientes, llamadas, correos y reuniones asociadas a los leads." /><div className="grid gap-4 xl:grid-cols-[0.9fr_1.1fr]"><Card><h2 className="text-xl font-black">Nueva actividad</h2><div className="mt-5 grid gap-3"><Select value={form.leadId} onChange={(e) => setForm({ ...form, leadId: e.target.value })}>{leads.map((lead) => <option key={lead.id} value={lead.id}>{lead.title}</option>)}</Select><Input placeholder="Descripción" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><Select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as typeof form.type })}><option value="llamada">Llamada</option><option value="correo">Correo</option><option value="reunion">Reunión</option><option value="tarea">Tarea</option></Select><Input type="date" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} /><Button onClick={() => { if (!form.title) return; addActivity(form); setForm({ ...form, title: "" }); }}><Plus className="h-4 w-4" />Agregar actividad</Button></div></Card><Card><h2 className="text-xl font-black">Agenda de seguimiento</h2><div className="mt-5 space-y-3">{activities.map((activity) => <button key={activity.id} onClick={() => toggleActivity(activity.id)} className="flex w-full items-start justify-between gap-4 rounded-3xl border border-stone-200 bg-stone-50 p-4 text-left transition hover:border-stone-400"><div><p className={activity.completed ? "font-black text-stone-400 line-through" : "font-black"}>{activity.title}</p><p className="mt-1 text-sm capitalize text-stone-600">{activity.type} · {prettyDate(activity.dueDate)}</p></div><CheckCircle2 className={activity.completed ? "h-5 w-5 text-stone-900" : "h-5 w-5 text-stone-300"} /></button>)}</div></Card></div></>; }
