import { Plus } from "lucide-react";
import { useState } from "react";
import { Button } from "../components/ui/Button";
import { Card } from "../components/ui/Card";
import { Input } from "../components/ui/Input";
import { PageHeader } from "../components/ui/PageHeader";
import { Select } from "../components/ui/Select";
import { useCrmStore } from "../store/crmStore";
export function ContactsPage() { const customers = useCrmStore((state) => state.customers); const contacts = useCrmStore((state) => state.contacts); const addContact = useCrmStore((state) => state.addContact); const [form, setForm] = useState({ customerId: customers[0]?.id ?? "", name: "", role: "", email: "", phone: "" }); return <><PageHeader eyebrow="CRM" title="Contactos" description="Personas asociadas a cada cliente para mantener el historial comercial ordenado." /><div className="grid gap-4 xl:grid-cols-[0.9fr_1.1fr]"><Card><h2 className="text-xl font-black">Nuevo contacto</h2><div className="mt-5 grid gap-3"><Select value={form.customerId} onChange={(e) => setForm({ ...form, customerId: e.target.value })}>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.company}</option>)}</Select><Input placeholder="Nombre" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><Input placeholder="Cargo / rol" value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} /><Input placeholder="Correo" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><Input placeholder="Teléfono" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><Button onClick={() => { if (!form.name || !form.customerId) return; addContact(form); setForm({ ...form, name: "", role: "", email: "", phone: "" }); }}><Plus className="h-4 w-4" />Guardar contacto</Button></div></Card><Card><h2 className="text-xl font-black">Contactos registrados</h2><div className="mt-5 grid gap-3">{contacts.map((contact) => { const customer = customers.find((item) => item.id === contact.customerId); return <div key={contact.id} className="rounded-3xl border border-stone-200 bg-stone-50 p-4"><div className="flex flex-col gap-2 md:flex-row md:items-start md:justify-between"><div><p className="font-black">{contact.name}</p><p className="text-sm text-stone-600">{contact.role} · {customer?.company ?? "Sin cliente"}</p></div><div className="text-sm text-stone-600 md:text-right"><p>{contact.email}</p><p>{contact.phone}</p></div></div></div>; })}</div></Card></div></>; }
